# Generated by Django 4.1.3 on 2022-12-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.IntegerField()),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
            ],
        ),
    ]
